spring.application.name=agendamento-tarefas
spring.mongodb.uri=mongodb://localhost:27017/db_agendador

jwt.secret=339925975ea04da49841ae274a9ee0ec

usuario.url=http://localhost:8080

server.port=8082
